productName = "IOSH__CloudLoader"
version = "0.0.0"
identifier = "com.tauri.dev"

[build]
beforeDevCommand = "cd frontend-svelte && npm run dev"
beforeBuildCommand = "cd frontend-svelte && npm run build"
devUrl = "http://localhost:1420"
frontendDist = "../build"

[app]
  [[app.windows]]
  title = "Cloud Loader"
  width = 800
  height = 600

  [app.security]
  csp = inf

[bundle]
  active = true
  targets = "all"
  icon = [
    "../frontend-svelte/static/icons/32x32.png",
    "../frontend-svelte/static/icons/128x128.png",
    "../frontend-svelte/static/icons/128x128@2x.png",
    "../frontend-svelte/static/icons/icon.icns",
    "../frontend-svelte/static/icons/icon.ico"
  ]

  [bundle.resources]
  "../secret/oauth/client_secret.json" = "config/client_secret.json"
